model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.TwoStreamControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 10
    timesteps: 1000
    first_stage_key: "image"
    cond_stage_key: "caption"
    control_key: "hint"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    sync_path: '/export/data/vislearn/rother_subgroup/feiden/models/pretrained/stable_diffusion/v2-1_512-ema-pruned.ckpt'
    # sync_path: '/home/hd/hd_hd/hd_ud441/diffusionModels/latent_diffusion/logs/pretrained/v2-1_512-ema-pruned.ckpt'
    # sync_path: null
    synch_control: False
    control_mode: 'light'

    control_stage_config:
      target: ldm.modules.diffusionmodules.twoStreamControl.TwoStreamControlNet
      params:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        hint_channels: 6
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 8 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
        infusion2control: 'cat'
        infusion2base: 'add'
        guiding: 'encoder_double'
        two_stream_mode: 'cross'
        control_model_ratio: 0.0125
        learn_embedding: False




    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel #cldm.cldm.ControlledUnetModel
      params:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          #attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 10
    num_workers: 10
    wrap: false
    train:
      target: ldm.data.synthetic_data.BlockWorldTrain
      params:
        control: ['Depth', 'Env']
        full_set: False
        data_start: 0
        data_stop: 100
    validation:
      target: ldm.data.synthetic_data.BlockWorldValidation
      params:
        control: ['Depth', 'Env']
        full_set: False
        data_start: 50_000
        data_stop: 50_010

        
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5
        max_images: 8
        increase_log_steps: False
    metrics_over_trainsteps_checkpoint:
        every_n_train_steps: None
        verbose: True
        save_top_k: 1
        filename: "best"

  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    accelerator: cuda
    max_steps: 500000
    devices: 5, #1,2,3